//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.CreditLines = new HashSet<CreditLines>();
            this.CreditLines1 = new HashSet<CreditLines>();
            this.MoveFunds = new HashSet<MoveFunds>();
            this.MoveFunds1 = new HashSet<MoveFunds>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Number { get; set; }
        public string Description { get; set; }
        public decimal Balance { get; set; }
        public int ContractorsID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> Type { get; set; }
        public int UsersID { get; set; }
    
        public virtual Сontractors Сontractors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditLines> CreditLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditLines> CreditLines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveFunds> MoveFunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveFunds> MoveFunds1 { get; set; }
    }
}
