//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditLines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditLines()
        {
            this.CreditLineDetails = new HashSet<CreditLineDetails>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> IsClose { get; set; }
        public decimal AllAmount { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<int> CountPays { get; set; }
        public Nullable<int> PeriodPaysType { get; set; }
        public int CreditorAccountsID { get; set; }
        public int BorrowerAccountsID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public int UsersID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts Accounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditLineDetails> CreditLineDetails { get; set; }
    }
}
