//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline
{
    using System;

    public partial class MoveFundDetails
    {
        public int ID { get; set; }
        public int MoveFundsID { get; set; }
        public int ReasonsID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public int UsersID { get; set; }
    
        public virtual MoveFunds MoveFunds { get; set; }
        public virtual Reasons Reasons { get; set; }
    }
}
