//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reasons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reasons()
        {
            this.MoveFundDetails = new HashSet<MoveFundDetails>();
            this.ReasonSynonyms = new HashSet<ReasonSynonyms>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> BarcodeEAN13 { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type_ { get; set; }
        public int ReasonGroupsID { get; set; }
        public Nullable<int> UnitsID { get; set; }
        public int UsersID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveFundDetails> MoveFundDetails { get; set; }
        public virtual ReasonGroups ReasonGroups { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReasonSynonyms> ReasonSynonyms { get; set; }
    }
}
