//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline
{
    using System;

    public partial class Users
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public string FIO { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<int> Type { get; set; }
        public int UserGroupsID { get; set; }
        public string AspNetUserID { get; set; }
    
        public virtual UserGroups UserGroups { get; set; }
    }
}
