//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сontractors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сontractors()
        {
            this.Accounts = new HashSet<Accounts>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string PersonSurname { get; set; }
        public string PersonMiddleName { get; set; }
        public string PersonName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> TownsID { get; set; }
        public string Address { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string WebSiteURL { get; set; }
        public string EMail { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> Type1 { get; set; }
        public Nullable<int> Type2 { get; set; }
        public Nullable<int> СontractorTypesID { get; set; }
        public int СontractorGroupsID { get; set; }
        public int UsersID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounts> Accounts { get; set; }
        public virtual Towns Towns { get; set; }
        public virtual СontractorGroups СontractorGroups { get; set; }
        public virtual СontractorTypes СontractorTypes { get; set; }
    }
}
